# camrest_config.yaml

## Where the samples will be written
save_data: run/5/camrest
save_model: run/5/model

## Where the vocab(s) will be written
src_vocab: run/vocab.src
tgt_vocab: run/vocab.tgt

save_checkpoint_steps: 12500
valid_steps: 12500
train_steps: 50000

seed: 42

# Batching
world_size: 2
gpu_ranks: [0, 1]
batch_size: 16
valid_batch_size: 16
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
optim: "adam"
learning_rate: 0.0000625
# warmup_steps: 10000
# decay_method: "noam"
# adam_beta2: 0.998
max_grad_norm: 1
label_smoothing: 0.1
param_init: 0
param_init_glorot: true

# Model
encoder_type: brnn
rnn_type : GRU
decoder_type: transformer
position_encoding: true
layers: 6
heads: 8
rnn_size: 768
word_vec_size: 768
transformer_ff: 3072
dropout_steps: [0]
dropout: 0.1
attention_dropout: 0.1

# Corpus opts:
data:
    corpus_1:
        path_src: data/src-train.txt
        path_tgt: data/tgt-train.txt
    valid:
        path_src: data/src-dev.txt
        path_tgt: data/tgt-dev.txt
